apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: theater-msa
  namespace: istio-system
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  hosts:
  - "theater.27.96.156.180.nip.io"
  gateways:
  - cp-gateway
  http:
  - match:
    - uri:
        prefix: /deployment-status
    route:
    - destination:
        host: api-gateway.theater-msa.svc.cluster.local
        port:
          number: 8080
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: api-gateway.theater-msa.svc.cluster.local
        port:
          number: 8080
