apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: theater-msa
  namespace: theater-msa

resources:
- namespace.yaml
- redis.yaml
- user-service.yaml
- movie-service.yaml
- booking-service.yaml
- api-gateway.yaml
- ingress.yaml
- deploy.yaml
- istio-virtualservice.yaml
- istio-destinationrule.yaml

labels:
- pairs:
    app.kubernetes.io/name: theater-msa
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: microservice
    app.kubernetes.io/part-of: theater-system

images:
- name: user-service
  newName: harbor.{{DOMAIN}}/theater-msa/user-service
  newTag: "latest"
- name: movie-service
  newName: harbor.{{DOMAIN}}/theater-msa/movie-service
  newTag: "latest"
- name: booking-service
  newName: harbor.{{DOMAIN}}/theater-msa/booking-service
  newTag: "latest"
- name: api-gateway
  newName: harbor.{{DOMAIN}}/theater-msa/api-gateway
  newTag: "latest"

replicas:
- name: user-service
  count: 2
- name: movie-service
  count: 2
- name: booking-service
  count: 2
- name: api-gateway
  count: 2