apiVersion: v1
kind: Namespace
metadata:
  name: theater-msa
  labels:
    name: theater-msa
    environment: production
    istio-injection: enabled
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: theater-config
  namespace: theater-msa
data:
  REDIS_URL: "redis:6379"
  USER_SERVICE_URL: "http://user-service:8081"
  MOVIE_SERVICE_URL: "http://movie-service:8082"
  BOOKING_SERVICE_URL: "http://booking-service:8083"
  API_GATEWAY_PORT: "8080"