---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: theater-msa-sa
  namespace: theater-msa
  labels:
    app: theater-msa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: theater-msa-reader
  labels:
    app: theater-msa
rules:
- apiGroups: [""]
  resources: ["pods", "nodes", "services"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.istio.io"]
  resources: ["virtualservices", "destinationrules"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: theater-msa-binding
  labels:
    app: theater-msa
subjects:
- kind: ServiceAccount
  name: theater-msa-sa
  namespace: theater-msa
roleRef:
  kind: ClusterRole
  name: theater-msa-reader
  apiGroup: rbac.authorization.k8s.io